[package]
name = "plumb-ingest"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0.104"
bzip2 = "0.6.1"
flate2 = "1.1.10"
futures-util = "0.3.34"
httpdate = "1.0.3"
osmpbf = "0.3.8"
plumb-core = { version = "0.1.0", path = "../plumb-core" }
reqwest = { version = "0.13.5", default-features = false, features = ["rustls", "stream"] }
rusqlite = { version = "0.40.2", features = ["bundled"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sevenz-rust2 = { version = "0.23.0", default-features = false, features = ["bzip2", "ppmd"] }
tar = "0.4.46"
tokio = { version = "1.53.1", features = ["full"] }
tracing = "0.1.44"
url = "2.5.8"
zip = "8.6.0"

[dev-dependencies]
tempfile = "3.27.0"
